import sys
import json
import time
import argparse
from pathlib import Path
from zoneinfo import ZoneInfo
from datetime import datetime

import yfinance as yf
import pandas as pd

from src.sp500_tickers import SP500_TICKERS

WATCHLIST_PATH = Path("watchlist.txt")
DEFAULT_MIN_GAP_PCT = 3.0
DEFAULT_MIN_PRICE = 3.0
MAX_SURVIVORS = 20
ET = ZoneInfo("America/New_York")


def _to_yahoo(ticker: str) -> str:
    return ticker.replace(" ", "-")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-gap", type=float, default=DEFAULT_MIN_GAP_PCT)
    parser.add_argument("--min-price", type=float, default=DEFAULT_MIN_PRICE)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    yahoo_tickers = [_to_yahoo(t) for t in SP500_TICKERS]
    total = len(yahoo_tickers)
    start_time = time.time()

    try:
        data = yf.download(
            tickers=" ".join(yahoo_tickers),
            period="2d",
            interval="1d",
            group_by="ticker",
            threads=5,
            progress=False,
            auto_adjust=True,
        )
    except Exception as e:
        result = {
            "success": False,
            "error": f"yf.download failed: {e}",
            "elapsed_seconds": round(time.time() - start_time, 2),
        }
        print(json.dumps(result))
        sys.exit(1)

    if data is None or data.empty:
        result = {
            "success": False,
            "error": "yf.download returned empty DataFrame",
            "elapsed_seconds": round(time.time() - start_time, 2),
        }
        print(json.dumps(result))
        sys.exit(1)

    survivors = []
    below_gap = 0
    below_price = 0
    failed = 0

    for ticker in yahoo_tickers:
        try:
            if ticker not in data.columns.levels[0] if isinstance(data.columns, pd.MultiIndex) else ticker not in data.columns:
                failed += 1
                continue

            bars = data[ticker]

            yesterday_close = bars["Close"].iloc[-2]
            today_open = bars["Open"].iloc[-1]
            today_close = bars["Close"].iloc[-1]
            today_high = bars["High"].iloc[-1]
            today_low = bars["Low"].iloc[-1]

            yesterday_close = float(yesterday_close)
            today_open = float(today_open)
            today_close = float(today_close)

            if today_close < args.min_price:
                below_price += 1
                continue

            gap_pct = (today_close - yesterday_close) / yesterday_close * 100.0

            if gap_pct < args.min_gap:
                below_gap += 1
                continue

            survivors.append({
                "ticker": ticker,
                "gap_pct": gap_pct,
                "open": today_open,
                "prev_close": yesterday_close,
            })
        except (KeyError, IndexError, ValueError, TypeError):
            failed += 1
            continue

    survivors.sort(key=lambda s: s["gap_pct"], reverse=True)
    survivors = survivors[:MAX_SURVIVORS]

    watchlist_path = None

    if not args.dry_run:
        now_et = datetime.now(ET)
        lines = [
            f"# Auto-generated by morning_prefilter.py at {now_et.strftime('%Y-%m-%d %H:%M')} ET",
            f"# Filters: gap >= {args.min_gap}%, price >= ${args.min_price}",
            "# Source: yfinance (screening only); Alpaca handles execution",
            f"# Survivors: {len(survivors)} (capped at {MAX_SURVIVORS}) of {total}",
            "#",
            "# ticker  # gap +X.XX%  open $X.XX  prev $X.XX",
        ]
        for s in survivors:
            lines.append(
                f"{s['ticker']}  # gap +{s['gap_pct']:.2f}%  "
                f"open ${s['open']:.2f}  prev ${s['prev_close']:.2f}"
            )
        WATCHLIST_PATH.write_text("\n".join(lines) + "\n")
        watchlist_path = str(WATCHLIST_PATH.resolve())

    elapsed = round(time.time() - start_time, 2)

    failed_pct = failed / total if total > 0 else 0
    if failed_pct >= 0.95:
        print(
            "ALERT: Yahoo-wide failure suspected; check yfinance changelog",
            file=sys.stderr,
        )
    elif failed_pct >= 0.30:
        print(
            f"ALERT: yfinance degradation (failed {failed}/{total})",
            file=sys.stderr,
        )

    result = {
        "success": True,
        "total_screened": total,
        "survivors_count": len(survivors),
        "below_gap": below_gap,
        "below_price": below_price,
        "failed": failed,
        "elapsed_seconds": elapsed,
        "top_20_survivors": [
            f"{s['ticker']} (+{s['gap_pct']:.2f}%)"
            for s in survivors
        ],
        "watchlist_path": watchlist_path,
    }
    print(json.dumps(result))


if __name__ == "__main__":
    main()
